### ISSUE TITLE
Discuss authentication method for VDM

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/worldcereal-vdm#8]
@VincentVerelst will schedule a first technical meeting with @soxofaan, @mbabic84 and a technical Gisat colleague to discuss authentication.

**Comment by soxofaan** [comment]
FYI: we had a meeting yesterday to clarify the approach (using OIDC authorization code flow with CDSE keycloak identity provider, so that VDM obtains user's access token, which it can forward to the openEO backend to access job metadata and results).

One thing I can help with is set up an OIDC client in CDSE keycloak to be used. But for that I need some info about the (target) VDM deployments: what redirect URI to use and what domains that will be used (for CORS allow-listing).
I created  a ticket about that for me at
-  https://github.com/WorldCereal/worldcereal-vdm/issues/9
